declare module "@formfusion/licence-plates" {
  type LicencePlates = {
    AF: string;
    AL: string;
    DZ: string;
    AD: string;
    AO: string;
    AG: string;
    AR: string;
    AM: string;
    AU: string;
    AT: string;
    AZ: string;
    BS: string;
    BH: string;
    BD: string;
    BB: string;
    BY: string;
    BE: string;
    BZ: string;
    BJ: string;
    BT: string;
    BO: string;
    BA: string;
    BW: string;
    BR: string;
    BN: string;
    BG: string;
    BF: string;
    BI: string;
    CV: string;
    KH: string;
    CM: string;
    CA: string;
    CF: string;
    TD: string;
    CL: string;
    CN: string;
    CO: string;
    KM: string;
    CD: string;
    CG: string;
    CR: string;
    CI: string;
    HR: string;
    CU: string;
    CY: string;
    CZ: string;
    DK: string;
    DJ: string;
    DM: string;
    DO: string;
    TL: string;
    EC: string;
    EG: string;
    SV: string;
    GQ: string;
    ER: string;
    EE: string;
    SZ: string;
    ET: string;
    FJ: string;
    FI: string;
    FR: string;
    GA: string;
    GM: string;
    GE: string;
    DE: string;
    GH: string;
    GR: string;
    GD: string;
    GT: string;
    GN: string;
    GW: string;
    GY: string;
    DE: string;
    LI: string;
    IN: string;
    AR: string;
    FI: string;
    HU: string;
    BR: string;
    PT: string;
    SE: string;
  };

  type LowercaseKeys<T> = {
    [K in keyof T as K extends string ? Lowercase<K> : never]: T[K];
  };

  const licencePlates: LowercaseKeys<LicencePlates>;

  export = licencePlates;
}
